import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("energy_data.csv")
df['Date'] = pd.to_datetime(df['Date'])

# Basic stats
print("Average energy generated (kWh) - January 2025:")
print(df[['Solar_kWh', 'Wind_kWh', 'Hydro_kWh']].mean())

# Max generation days
print("\nMax solar day (January 2025):", df.loc[df['Solar_kWh'].idxmax(), 'Date'].date())
print("Max wind day (January 2025):", df.loc[df['Wind_kWh'].idxmax(), 'Date'].date())
print("Max hydro day (January 2025):", df.loc[df['Hydro_kWh'].idxmax(), 'Date'].date())

# Pie Chart - Total Contribution
total = df[['Solar_kWh','Wind_kWh','Hydro_kWh']].sum()
plt.figure(figsize=(6,6))
plt.pie(total, labels=total.index, autopct='%1.1f%%', startangle=90)
plt.title("Total Energy Contribution - January 2025")
plt.show()

# Line Chart - Daily Trends
df_melted = pd.melt(df, id_vars=['Date'], value_vars=['Solar_kWh', 'Wind_kWh', 'Hydro_kWh'])
plt.figure(figsize=(10,6))
sns.lineplot(x='Date', y='value', hue='variable', data=df_melted, marker='o')
plt.title("Daily Renewable Energy Generation - January 2025")
plt.xlabel("Date")
plt.ylabel("Energy (kWh)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Bar Chart - Total Generation by Source
plt.figure(figsize=(8,6))
sns.barplot(x=total.index, y=total.values, palette="viridis")
plt.title("Total Energy Generated by Source - January 2025")
plt.xlabel("Energy Source")
plt.ylabel("Total kWh")
for i, v in enumerate(total.values):
    plt.text(i, v + 2, str(v), ha='center', fontweight='bold')  # Display value on bar
plt.show()